server:
  port: 13001
  tomcat:
    uri-encoding: UTF-8
  context-path: /ESB
  
logging:
  file: D://ESB-13001.log
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka
  instance:
    instance-id: ServiceBus-server-13001
    prefer-ip-address: true
    
info:
  app.name: ServiceBus-server-13001
  company.name: ESB Project
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  mvc:
    date-format: yyyy-MM-dd
  application:
    name: ServiceBus-server-13001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.52.117.118:3306/esb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: esb
    password: esb
    dbcp2:
      min-idle: 3
      initial-size: 3
      max-total: 500
      max-wait-millis: 200
---
spring:
  profiles: release
  mvc:
    date-format: yyyy-MM-dd
  application:
    name: ServiceBus-server-13001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/esb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
    dbcp2:
      min-idle: 3
      initial-size: 3
      max-total: 500
      max-wait-millis: 200
